# GitHub Actions for deploying a Python app to Azure Web App using Oryx

name: Build and Deploy Python App to Azure Web App using Oryx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHubリポジトリからコードをチェックアウト
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v4

      # 2. Set up Node.js (Oryx requires Node.js to function)
      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # 必要に応じてNode.jsバージョンを指定

      # 3. Install Oryx
      - name: 'Install Oryx'
        run: |
          curl -L https://github.com/microsoft/Oryx/releases/download/20230310.2/oryx-linux-x64.tar.gz -o oryx-linux-x64.tar.gz
          tar -xvzf oryx-linux-x64.tar.gz
          sudo mv oryx /usr/local/bin/

      # 4. Run Oryx Build
      - name: 'Run Oryx Build'
        run: |
          oryx build . --platform python --platform-version 3.11

      # 5. Azureへのデプロイ
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen-7-step4-prelesson-1'  # Azure Web Appの名前
          slot-name: 'Production'  # 必要に応じてデプロイスロットを指定
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30DF7C15451A4F7C8D10250582404692 }}  # Azureの公開プロファイルをGitHub Secretsで指定
